import { Place, Vibe } from "./types";

export const places: Place[] = [
  {
    id: "farmyard",
    name: "Farmyard",
    cat: "restaurant",
    cuisine: ["british", "modern european"],
    area: "st leonards",
    price: "£££",
    vibes: ["date night", "night out"],
    desc:
      "Steak, bone marrow, crevettes and oysters washed down with natty wine. Seasonal, farm-to-table cooking at its best.",
    tip: "The tasting menu and wine pairings are worth the splurge. Book ahead.",
    booking: "recommended",
    dog: "no",
    kids: "not ideal",
    open: ["wed", "thu", "fri", "sat"],
    pick: true,
    is_new: false,
    ph: "ph-1",
  },
  {
    id: "lury",
    name: "Lury",
    cat: "restaurant",
    cuisine: ["sri lankan", "tasting menu"],
    area: "new town",
    price: "£££",
    vibes: ["date night", "sea views"],
    desc:
      "Spectacular Sri Lankan inspired 12-14 course tasting menu. Head chef used to work at Le Manoir. £82 a head and worth every penny.",
    tip:
      "This is the place for a special date night. Nothing else like it on the coast.",
    booking: "essential",
    dog: "no",
    kids: "not ideal",
    open: ["thu", "fri", "sat"],
    pick: true,
    is_new: true,
    ph: "ph-5",
  },
  {
    id: "coquina",
    name: "Coquina",
    cat: "restaurant",
    cuisine: ["modern european"],
    area: "old town",
    price: "££",
    vibes: ["date night", "sea views"],
    desc:
      "Beautiful views from Rockanore and gorgeous plates of goodness. The kind of place where everything just works.",
    tip: "Try the polenta and the asparagus.",
    booking: "recommended",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: true,
    ph: "ph-1",
  },
  {
    id: "bayte",
    name: "Bayte",
    cat: "restaurant",
    cuisine: ["italian", "seafood"],
    area: "st leonards",
    price: "££",
    vibes: ["date night", "vegan friendly"],
    desc:
      "Owned by the Petersham Nurseries family. Contemporary Italian with a real focus on seafood. Lovingly prepared, beautifully presented.",
    tip: "Pasta night on Monday is a great shout.",
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "three-faces",
    name: "Three Faces of Del Parc",
    cat: "restaurant",
    cuisine: ["modern european"],
    area: "st leonards",
    price: "££",
    vibes: ["date night", "night out"],
    desc:
      "No ala carte — they work around dietaries and you get what you get, which is always brilliant. The music is lit and loudish so leave your kids at home. Feels like you got an invite to the best house party.",
    tip: "You must try the cheesecake. Seriously.",
    booking: "essential",
    dog: "no",
    kids: "no",
    open: ["fri", "sat"],
    pick: true,
    is_new: false,
    ph: "ph-7",
  },
  {
    id: "st-clements",
    name: "St Clements",
    cat: "restaurant",
    cuisine: ["british", "bistro"],
    area: "st leonards",
    price: "££",
    vibes: ["date night"],
    desc:
      "Perfect bistro for a cosy date night. Great front of house, honest cooking, the kind of place you keep coming back to.",
    tip: null,
    booking: "recommended",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: true,
    is_new: false,
    ph: "ph-3",
  },
  {
    id: "crown",
    name: "The Crown",
    cat: "restaurant",
    cuisine: ["british", "plant-based"],
    area: "old town",
    price: "££",
    vibes: ["family friendly", "vegan friendly"],
    desc:
      "Really good gastro pub food with lots of healthy and plant-based options. Focus on seasonality. One of the few reliably open on Monday and Tuesday.",
    tip: null,
    booking: "walk-in",
    dog: "yes",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-4",
  },
  {
    id: "porters",
    name: "Porters",
    cat: "restaurant",
    cuisine: ["british"],
    area: "old town",
    price: "££",
    vibes: ["family friendly"],
    desc:
      "Traditional fayre done well in a family friendly setting. Sunday roasts are a strong move here.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "liban-coast",
    name: "Liban Coast",
    cat: "restaurant",
    cuisine: ["lebanese", "middle eastern"],
    area: "st leonards",
    price: "££",
    vibes: ["family friendly", "vegan friendly"],
    desc:
      "You can taste the love here. Falafels are beautiful, mezze is generous, and everything feels homemade because it is.",
    tip: "Get the chicken main — it's a transcendental experience.",
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "sumisu",
    name: "Sumisu Ramen",
    cat: "restaurant",
    cuisine: ["japanese", "ramen"],
    area: "new town",
    price: "££",
    vibes: ["vegan friendly"],
    desc:
      "The best ramen, with meat provided from Beak & Tail. Warming, filling, exactly what you want on a grey day.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-8",
  },
  {
    id: "kassa",
    name: "Kassa",
    cat: "restaurant",
    cuisine: ["afghani"],
    area: "st leonards",
    price: "££",
    vibes: ["family friendly"],
    desc:
      "Stick to the traditional Afghani dishes and you won't be disappointed. Curries and stews all win.",
    tip: "Try the chicken zerensk — a beautiful berry jewelled rice dish.",
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "tonka",
    name: "Tonka",
    cat: "restaurant",
    cuisine: ["mauritian", "fusion"],
    area: "old town",
    price: "££",
    vibes: ["coffee & pastries", "family friendly"],
    desc:
      "Mauritian-inspired fusion menu with delicious iced coffees and matcha and yummy fun cakes.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: true,
    ph: "ph-7",
  },
  {
    id: "ladle",
    name: "Ladle",
    cat: "restaurant",
    cuisine: ["italian", "pasta"],
    area: "old town",
    price: "££",
    vibes: ["date night"],
    desc:
      "Beautiful pasta plates from their micro kitchen. Small, intimate, and everything is made with care.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "not ideal",
    open: ["thu", "fri", "sat"],
    pick: false,
    is_new: true,
    ph: "ph-3",
  },
  {
    id: "winifreds",
    name: "Winifred's",
    cat: "restaurant",
    cuisine: ["modern european", "seasonal"],
    area: "seafront",
    price: "££",
    vibes: ["date night", "sea views"],
    desc:
      "Great early reviews from this place at Source Park. Eclectic menu of fresh and seasonal ingredients.",
    tip: "Go for the wine, stay for the small plates.",
    booking: "recommended",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: true,
    ph: "ph-1",
  },
  {
    id: "shiosai",
    name: "Shiosai Sushi",
    cat: "restaurant",
    cuisine: ["japanese", "sushi"],
    area: "seafront",
    price: "£££",
    vibes: ["date night"],
    desc:
      "Andrew Wong from The Seadog has opened this spot at Source Park serving up the most beautiful sushi and sake.",
    tip: null,
    booking: "recommended",
    dog: "no",
    kids: "yes",
    open: ["thu", "fri", "sat", "sun"],
    pick: false,
    is_new: true,
    ph: "ph-5",
  },
  {
    id: "albo",
    name: "Albo",
    cat: "restaurant",
    cuisine: ["european", "small plates"],
    area: "st leonards",
    price: "££",
    vibes: ["date night", "night out"],
    desc:
      "Used to be Wavey Bar, now on St Leonards high street. Super yummy European style small plates packed with goodness.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat"],
    pick: false,
    is_new: true,
    ph: "ph-4",
  },
  {
    id: "boatyard",
    name: "Boatyard at Heist",
    cat: "restaurant",
    cuisine: ["seafood"],
    area: "st leonards",
    price: "££",
    vibes: ["date night", "sea views"],
    desc:
      "Innovative seafood dishes from across all cuisines, delicious wines and brilliant front of house.",
    tip: null,
    booking: "recommended",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-8",
  },
  {
    id: "arigato",
    name: "Arigato",
    cat: "restaurant",
    cuisine: ["japanese"],
    area: "st leonards",
    price: "££",
    vibes: ["vegan friendly"],
    desc:
      "Delicious salmon teriyaki don, sashimi, gyoza and sake. Reliable and always good.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat"],
    pick: true,
    is_new: false,
    ph: "ph-1",
  },
  {
    id: "beacon",
    name: "The Beacon",
    cat: "restaurant",
    cuisine: ["british"],
    area: "west hill",
    price: "££",
    vibes: ["family friendly", "dog friendly", "sea views"],
    desc:
      "Very child friendly with enclosed garden, gorgeous views and sound system. Sunday roasts are a highlight.",
    tip: "Parking is challenging — taxi or walk.",
    booking: "recommended",
    dog: "yes",
    kids: "highchairs & garden",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-4",
  },
  {
    id: "royal",
    name: "The Royal",
    cat: "restaurant",
    cuisine: ["british", "plant-based"],
    area: "st leonards",
    price: "£££",
    vibes: ["date night", "vegan friendly"],
    desc:
      "Seasonally themed with both plant-based and ala carte options. High end gastro pub vibe.",
    tip: null,
    booking: "recommended",
    dog: "yes",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-3",
  },
  {
    id: "bella-vista",
    name: "Bella Vista",
    cat: "restaurant",
    cuisine: ["italian", "seafood"],
    area: "st leonards",
    price: "££",
    vibes: ["family friendly", "date night"],
    desc:
      "Lovingly prepared food with all the classics as well as some unique seafood offerings. Some mixed reviews but we rate it.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "ceylon-cafe",
    name: "Ceylon Cafe",
    cat: "restaurant",
    cuisine: ["sri lankan"],
    area: "bohemia",
    price: "££",
    vibes: ["family friendly", "vegan friendly"],
    desc:
      "Great for kids as they offer more low key options. Sri Lankan home cooking done right.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "rituals",
    name: "Rituals",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["night out", "sea views", "date night"],
    desc:
      "Newly opened with beautiful interiors and a sea vista at the Marina. Cocktails with a view.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "not ideal",
    open: ["thu", "fri", "sat", "sun"],
    pick: false,
    is_new: true,
    ph: "ph-1",
  },
  {
    id: "cactus-hound",
    name: "Cactus Hound",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["night out"],
    desc:
      "Spicy margs with an eclectic mix of people, loud music and dancing. The kind of place where anything can happen.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "no",
    open: ["thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-7",
  },
  {
    id: "wermut",
    name: "Wermut at Sleeper",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["date night", "night out"],
    desc:
      "Bagel shop by day, gorgeous cocktails by night. Specialising in bitters, aperitivi and vermouths.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "no",
    open: ["fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "collected-fictions",
    name: "Collected Fictions",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["date night"],
    desc:
      "Natural wine bar. Natty buffs unite. Intimate, knowledgeable, and always pouring something interesting.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "no",
    open: ["thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-5",
  },
  {
    id: "graze",
    name: "Graze on The Grand",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["date night"],
    desc:
      "Wine, meats, cheese, pickles and some bigger plates too. What's not to love.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "bar40",
    name: "Bar40",
    cat: "bar",
    cuisine: null,
    area: "st leonards",
    price: "££",
    vibes: ["night out", "date night"],
    desc:
      "Great cocktails and small plates. Relaxed vibe that can go either way — quiet drink or big night.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "no",
    open: ["wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-8",
  },
  {
    id: "seed",
    name: "Seed",
    cat: "bar",
    cuisine: null,
    area: "old town",
    price: "££",
    vibes: ["night out", "vegan friendly"],
    desc:
      "Tapas bar in the Old Town. Good drinks, shareable plates, buzzy atmosphere.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "not ideal",
    open: ["thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-4",
  },
  {
    id: "noahs-goat",
    name: "Noah's Goat",
    cat: "bar",
    cuisine: null,
    area: "old town",
    price: "££",
    vibes: ["date night", "coffee & pastries"],
    desc:
      "Wine shop and café bar. Browse the shelves, pick a bottle, drink it there. Simple and lovely.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-3",
  },
  {
    id: "sleeper",
    name: "Sleeper",
    cat: "café",
    cuisine: ["bagels"],
    area: "st leonards",
    price: "£",
    vibes: ["breakfast", "coffee & pastries"],
    desc:
      "Great bagels and lovely artisan goods sold in-store. Turns into Wermut cocktail bar at night.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-3",
  },
  {
    id: "sonnys",
    name: "Sonny's",
    cat: "café",
    cuisine: ["seafood", "brunch"],
    area: "st leonards",
    price: "£",
    vibes: ["breakfast", "family friendly"],
    desc:
      "Fishmonger with excellent breakfast and brunch. Basic filter coffee but the food more than makes up for it.",
    tip: "The kedgeree is insanely good.",
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: true,
    is_new: false,
    ph: "ph-8",
  },
  {
    id: "folks",
    name: "Folks",
    cat: "café",
    cuisine: ["coffee", "pastries"],
    area: "st leonards",
    price: "£",
    vibes: ["coffee & pastries", "breakfast"],
    desc:
      "Great coffee and pastries. Simple, well executed, no fuss.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-4",
  },
  {
    id: "fika",
    name: "Fika",
    cat: "café",
    cuisine: ["coffee", "cakes"],
    area: "st leonards",
    price: "£",
    vibes: ["coffee & pastries", "vegan friendly"],
    desc:
      "Lots of hot drink options including matcha and golden latte. Gorgeous cakes, soups and salads.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "dark-circles",
    name: "Dark Circles",
    cat: "café",
    cuisine: ["coffee"],
    area: "st leonards",
    price: "£",
    vibes: ["coffee & pastries"],
    desc:
      "Dig and sift through records whilst you sip. Coffee and vinyl — what more do you need.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-8",
  },
  {
    id: "forage-fleur",
    name: "Forage & Fleur",
    cat: "café",
    cuisine: ["brunch"],
    area: "bohemia",
    price: "£",
    vibes: ["breakfast", "coffee & pastries"],
    desc:
      "Also a florist and hairdresser with a secret garden. Unexpected and lovely.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-7",
  },
  {
    id: "sturdee",
    name: "Sturdee On The Rocks",
    cat: "café",
    cuisine: ["breakfast", "fry up"],
    area: "old town",
    price: "£",
    vibes: ["breakfast", "family friendly"],
    desc:
      "When only a fry up will do. No frills, proper breakfast, job done.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "bonjour",
    name: "Bonjour",
    cat: "café",
    cuisine: ["brunch", "pancakes"],
    area: "st leonards",
    price: "£",
    vibes: ["breakfast", "family friendly"],
    desc:
      "Great place to take your kids for pancakes. Bubble and squeak also good.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    pick: false,
    is_new: false,
    ph: "ph-2",
  },
  {
    id: "good-bean",
    name: "Good Bean at Goodmans",
    cat: "café",
    cuisine: ["coffee"],
    area: "st leonards",
    price: "£",
    vibes: ["coffee & pastries"],
    desc:
      "Get a haircut, grab a coffee. An unlikely combo that somehow works.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-1",
  },
  {
    id: "maker-baker",
    name: "Maker & Baker",
    cat: "bakery",
    cuisine: ["sourdough", "pastries"],
    area: "new town",
    price: "£",
    vibes: ["coffee & pastries", "breakfast"],
    desc:
      "Amazing bakery. The sourdough and pastries are next level.",
    tip: "Expect queues at weekends.",
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat", "sun"],
    pick: true,
    is_new: false,
    ph: "ph-3",
  },
  {
    id: "judges",
    name: "Judges",
    cat: "bakery",
    cuisine: ["bread", "pastries"],
    area: "new town",
    price: "£",
    vibes: ["coffee & pastries", "breakfast"],
    desc:
      "Solid neighbourhood bakery. Good bread, good pastries, no pretension.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["tue", "wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-6",
  },
  {
    id: "oak-bakery",
    name: "The Oak Bakery",
    cat: "bakery",
    cuisine: ["sourdough"],
    area: "st leonards",
    price: "£",
    vibes: ["coffee & pastries"],
    desc:
      "Another great local bakery keeping St Leonards in sourdough.",
    tip: null,
    booking: "walk-in",
    dog: "no",
    kids: "yes",
    open: ["wed", "thu", "fri", "sat"],
    pick: false,
    is_new: false,
    ph: "ph-4",
  },
];

export const vibeList: Vibe[] = [
  { name: "all", emoji: "" },
  { name: "dog friendly", emoji: "🐕" },
  { name: "family friendly", emoji: "👶" },
  { name: "date night", emoji: "❤️" },
  { name: "vegan friendly", emoji: "🌱" },
  { name: "night out", emoji: "🍺" },
  { name: "breakfast", emoji: "🥐" },
  { name: "sea views", emoji: "🌅" },
  { name: "coffee & pastries", emoji: "☕" },
];
